Development
AllenNeuralDynamics/aind-watchdog-service pull request #51
Opened 2024-08-22 19:49 UTC by arielleleon

- Initial, stable release of the aind-watchdog-service
- Better type-hinting in models
- Documentation for manual configuration of Task Scheduler
- Exposed more parameters in the manifest_config (force_cloud_sync, endpoint, etc)
- Optional values contain defaults
- Build in GitHub Actions

2024-08-22 22:41 UTC, bruno-f-cruz requested changes
Some minor points, but otherwise is looking great and almost ready to merge!

2024-08-22 22:41 UTC, bruno-f-cruz commented on src/aind_watchdog_service/event_handler.py
>              self.scheduler.remove_job(self.jobs[event.src_path].id)
Not sure what this "id" attribute is, but it doesn't not conform to the self.jobs typing above (i.e. Dict[str,str])

2024-08-22 22:41 UTC, bruno-f-cruz commented on src/aind_watchdog_service/event_handler.py
>              self._remove_job(self.jobs[event.src_path].id)
Same as above, typing is not consistent

2024-08-22 22:41 UTC, bruno-f-cruz commented on src/aind_watchdog_service/run_job.py
> -        self.alert_bot = AlertBot(self.watch_config.webhook_url)
This dependency injection pattern was actually great :P

2024-08-22 22:41 UTC, bruno-f-cruz commented on src/aind_watchdog_service/run_job.py
> +            alert_bot = AlertBot(self.watch_config.webhook_url)
The webhook_url seems to be nullable. A guard clause should be added here.

2024-08-22 22:41 UTC, bruno-f-cruz commented on src/aind_watchdog_service/run_job.py
>          submit_job_response = requests.post(
Can we add a 5-second timeout here? I know it shouldn't take that long, but it would make me feel better at night.

2024-08-23 17:38 UTC, arielleleon commented on .github/workflows/publish_exe.yml
> +  pull_request:
Good point. I will remove this now

2024-08-23 17:49 UTC, arielleleon commented on src/aind_watchdog_service/event_handler.py
> +    def _load_manifest(self, event: FileCreatedEvent) -> ManifestConfig:
This has been fixed

2024-08-23 19:11 UTC, arielleleon commented on src/aind_watchdog_service/event_handler.py
>              self.scheduler.remove_job(self.jobs[event.src_path].id)
remove job is actually unnecessary. Let me know what you think about the change

2024-08-23 19:11 UTC, arielleleon commented on src/aind_watchdog_service/event_handler.py
>              self._remove_job(self.jobs[event.src_path].id)
Same as above

2024-08-23 19:33 UTC, arielleleon commented on src/aind_watchdog_service/run_job.py
> +            alert_bot = AlertBot(self.watch_config.webhook_url)
This is already caught on the setting of send

2024-08-23 19:34 UTC, arielleleon commented on src/aind_watchdog_service/run_job.py
>          submit_job_response = requests.post(
@bruno-f-cruz After L223?

2024-08-23 19:37 UTC, bruno-f-cruz commented on src/aind_watchdog_service/run_job.py
>          submit_job_response = requests.post(
in the `request.post` method pass the kwarg : `timeout=5`

2024-08-23 19:39 UTC, bruno-f-cruz commented on README.md
> +* Create a watch_config file as yaml. Create an environment variable called WATCH_CONFIG containing the location of the config file.
Can't see it, but maybe we can add it afterward?

2024-08-23 21:09 UTC, bruno-f-cruz approved these changes

2024-08-23 21:31 UTC, merged